version: "3.9"

services:
  web:
    build:
      context: ..             
      dockerfile: ops/Dockerfile
    container_name: spa_frontend
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: spa_database
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: gs_ai
    volumes:
      - dbdata:/var/lib/mysql
      - ../db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  dbdata: